POST http://localhost:3333/user
Content-Type: application/json

{
   "cpf":"12345678920",
   "nome":"Arthur",
   "sobrenome":"Theodoro",
   "email":"arthur@mail.com",
   "telefone":"(11)988888888",
   "profissao":"Front end Dev",
   "senha":"123123123"
}


###

POST http://localhost:3333/post
Content-Type: application/json

{
   "title":"Teste",
   "content":"SALSDJKLSDAKJDSLKJSDAJKLDSAJKLSDAKJLSADJKLDASLJK",
   "creator":"Arthur Theodoro"
}


###

GET http://localhost:3333/posts


###

PUT  http://localhost:3333/post/b954c5b3-77eb-487c-a5af-094461448782
Content-Type: application/json

{
    "title":"Post 01",
    "content":"Atualizando o post"
    
}


###

DELETE  http://localhost:3333/post/b954c5b3-77eb-487c-a5af-094461448782


