POST http://localhost:3333/post
Content-Type: application/json

{
   "title":"Desvendando o node js",
   "content":"Aprendendo um pouco mais sobre como funciona o node js"
}


###

GET http://localhost:3333/posts


###

PUT  http://localhost:3333/post/b954c5b3-77eb-487c-a5af-094461448782
Content-Type: application/json

{
    "title":"Post 01",
    "content":"Atualizando o post"
    
}


###

DELETE  http://localhost:3333/post/b954c5b3-77eb-487c-a5af-094461448782


